autoridad_index:
    path:     /
    defaults: { _controller: "AppBundle:Autoridad:index" }
    methods:  GET

autoridad_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Autoridad:show" }
    methods:  GET

autoridad_new:
    path:     /new
    defaults: { _controller: "AppBundle:Autoridad:new" }
    methods:  [GET, POST]

autoridad_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Autoridad:edit" }
    methods:  [GET, POST]

autoridad_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Autoridad:delete" }
    methods:  DELETE
