concejalia_index:
    path:     /
    defaults: { _controller: "AppBundle:Concejalia:index" }
    methods:  GET

concejalia_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Concejalia:show" }
    methods:  GET

concejalia_new:
    path:     /new
    defaults: { _controller: "AppBundle:Concejalia:new" }
    methods:  [GET, POST]

concejalia_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Concejalia:edit" }
    methods:  [GET, POST]

concejalia_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Concejalia:delete" }
    methods:  DELETE
